### ISSUE TITLE
Light-themed option?

### ISSUE THREAD

**Issue by rnemec** [Borderliner/Meshki#11]
Hi, do you have any plans of releasing this with while/light background? Or do you have easy steps to switch and build locally?

**Comment by Borderliner** [comment]
Hello, and thanks for your feedback.

Currently, I don't have any plans for any light themes, since the whole purpose of Meshki is being eye-friendly, and light-themed Meshki would not fulfill that. It would be ironic, since Meshki is a Persian word, meaning "Black".
But feel free to fork the project, and change the colours inside `Meshki/src/scss/utils/variables/_colors.scss` to meet your demands.
Also, if the result happens to be good-looking, put your colours inside a different file, open a pull request, and I'll merge it as an alternative look-and-feel.

Cheers!

**Comment by rnemec** [comment]
Thanks! I'll experiment and see.

**Comment by Borderliner** [comment]
@rnemec Great news! Light theme is being planned for v3.0.0. Stay tuned.

**Comment by Borderliner** [comment]
![Screenshot_2023-11-26_01-48-55](https://github.com/Borderliner/Meshki/assets/2098879/581ec8b8-1a10-4de4-9475-c646f8baf4f3)

**Comment by Borderliner** [comment]
Just merged [v3.0.0](https://github.com/Borderliner/Meshki/tree/v3.0.0) which includes a light-theme option. Enjoy!
